server:
  port : 8082
  
spring:
  application:    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect        
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
#      bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka